services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1026:100 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      #程序默认语言
      - ND_DEFAULTLANGUAGE=zh-Hans
      #启用GRAVATAR头像
      - ND_ENABLEGRAVATAR=true
      #关闭转码，如需要转码请设置为true
      - ND_ENABLETRANSCODINGCONFIG=true
      #SPOTIFY相关
      # - ND_SPOTIFY_ID=
      # - ND_SPOTIFY_SECRET=
      #LAST.FM相关
      # - ND_LASTFM_LANGUAGE=zh
      # - ND_LASTFM_APIKEY=
      # - ND_LASTFM_SECRET=
      #PROXY相关
      - HTTP_PROXY=http://192.168.100.222:7890
      - HTTPS_PROXY=http://192.168.100.222:7890
    volumes:
      - "/volume1/docker/navidrome:/data"
      - "/volume1/Data/音乐:/music:ro"
