version: '3.3'
services:
    iperf3:
        container_name: iperf3-server
        ports:
            - '5201:5201'
        image: networkstatic/iperf3
        command: '-s'
        restart: unless-stopped