version: '3'
services:
    pingvin-share:
        image: stonith404/pingvin-share
        restart: unless-stopped
        ports:
        - 4006:3000
        volumes:
            - "/volume1/docker/pingvin-share/data:/opt/app/backend/data"
            - "/volume1/docker/pingvin-share/images:/opt/app/frontend/public/img"
        # Optional: If you add ClamAV, uncomment the following to have ClamAV start first.
        # depends_on:
        # clamav:
        # condition: service_healthy
        # Optional: Add ClamAV (see README.md)
        # ClamAV is currently only available for AMD64 see https://github.com/Cisco-Talos/clamav/issues/482
        # clamav:
        # restart: unless-stopped
        # image: clamav/clamav